"""
Tool Agent adapter for anukriti-pgx-core.

Sentinel Clinical is an investigation *orchestration* engine, not a
pharmacogenomics system. This module wraps `anukriti-pgx-core` (PyPI) the
same way we'd wrap a drug-interaction API or a lab-interpretation function:
it is one tool the Tool Agent can call, and its output is one evidence
stream among many (labs, FDA label, CPIC guidelines, drug interactions,
hospital notes, timeline) that flows into `InvestigationState.tool_outputs`
for the Hypothesis Agent to weigh — and, via `citations`, into the final
Reporter output for traceability.

Verified against the real installed package (anukriti-pgx-core==0.6.0):

    from anukriti_pgx_core.phenotype.clinical_action import details_for_action

    >>> details_for_action("DPYD", "Poor Metabolizer", "fluorouracil")
    {
        "action": "AVOID",
        "activity_score_range": "0 - 0.5",
        "recommendation": "Avoid fluorouracil. Select an alternative drug "
                           "not predominantly metabolised by DPD.",
        "dose_adjustment": "contraindicated",
        "citations": ["29152729"],
    }

`details_for_action` is the single source of truth here: it returns `{}`
uniformly whenever the tool cannot produce a grounded answer — missing
phenotype, empty phenotype, or an unmapped gene/phenotype/drug combination
(confirmed empirically against the installed package for all three cases).
That means the "insufficient evidence" refusal is generated by pgx-core
itself, not faked by this wrapper or by the Hypothesis Agent — the tool
returning `{}` *is* the Phase 3 "cannot confirm DPYD toxicity, need
genotype" behavior.

Important scope note: `details_for_action` takes an *already resolved*
phenotype label (e.g. "Poor Metabolizer"), not a raw diplotype or VCF.
Sentinel does not perform genotype-to-phenotype calling itself — that
determination is expected to arrive as evidence from an upstream source
(e.g. an EHR-attached genomic report retrieved by the Retrieval Agent).
"""

from __future__ import annotations

from typing import Optional, TypedDict

from anukriti_pgx_core.phenotype.clinical_action import details_for_action


class PgxToolResult(TypedDict):
    tool: str
    gene: str
    drug: str
    phenotype: Optional[str]
    action: str
    recommendation: str
    dose_adjustment: str
    activity_score_range: str
    citations: list
    status: str


def get_pharmacogenomic_recommendation(
    gene: str,
    drug: str,
    phenotype: Optional[str] = None,
) -> PgxToolResult:
    """
    Tool-Agent-callable wrapper around anukriti-pgx-core's clinical-action
    tier (`anukriti_pgx_core.phenotype.clinical_action.details_for_action`).

    Args:
        gene: Gene symbol, e.g. "DPYD".
        drug: Drug name, e.g. "fluorouracil". Normalized the same way
            pgx-core normalizes it internally (hyphen/underscore variants
            resolve consistently).
        phenotype: CPIC phenotype label already resolved elsewhere in the
            investigation's evidence (e.g. "Poor Metabolizer"). If this is
            None, empty, or the gene/phenotype/drug combination has no
            pinned CPIC-level mapping, `details_for_action` returns `{}`
            and this function reports `status: "insufficient_evidence"`
            rather than fabricating a recommendation.

    Returns:
        A structured evidence record for `InvestigationState.tool_outputs`.
        `citations` carries PMID(s) through to the Reporter for traceable,
        cite-backed statements in the final investigation report.
    """
    detail = details_for_action(gene, phenotype, drug)

    return PgxToolResult(
        tool="pgx-core",
        gene=gene,
        drug=drug,
        phenotype=phenotype,
        action=detail.get("action", ""),
        recommendation=detail.get("recommendation", ""),
        dose_adjustment=detail.get("dose_adjustment", ""),
        activity_score_range=detail.get("activity_score_range", ""),
        citations=detail.get("citations", []),
        status="confirmed" if detail else "insufficient_evidence",
    )
